config/routes.rb
Rails.application.routes.draw do
  
  root 'merchandises#index'

  resources :signup do
    collection do
      get 'step1'
      post 'step2'
      post 'step3'
      post 'step4'
      post 'step5'
    end
  end

  
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }
  
  resources :credit_card, only: [:create]
  resources :merchandises, only: [:index, :show] do
    resources :comments, only: [:create, :new]
    resources :likes, only: [:create, :destroy]
    resources :purchase, only: [:index, :create]
  end

  resources :exhibits, only: [:index, :create, :edit, :update, :show, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json'}
    end
  end

  resources :mypage, only: [:index]
  get '/mypage/profile' => 'mypage#edit'
  get '/mypage/card' => 'mypage#show'
  get '/mypage/card/create' => 'mypage#create'
  patch '/mypage' => 'mypage#update'
  get '/mypage/exhibit_list/list' => 'exhibit_list#list'
  get '/mypage/exhibit_list/dealing' => 'exhibit_list#dealing'
  get '/mypage/exhibit_list/complete' => 'exhibit_list#complete'

  resources :personal_informations, only: [:new, :create, :edit, :update]

  get '/signup' => 'signup#index'
  get '/logout' => 'logout#log_out'

  
end

app/models/address.rb
class Address < ApplicationRecord
  #validation制御回避のため、user_idに対してoptional: trueをつける
  belongs_to :user , optional: true

  def get_full_address
    self.prefecture.name + self.city + self.number
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  # step3入力項目
  validates :last_name,               presence: true
  validates :first_name,              presence: true
  validates :last_name_kana,          presence: true
  validates :first_name_kana,         presence: true
  validates :postal_code,             presence: true, format: { with: /\A\d{3}[-]\d{4}\z/ }
  validates :prefecture_id,           presence: true
  validates :city,                    presence: true
  validates :number,                  presence: true

end

app/models/balance.rb
class Balance < ApplicationRecord
  belongs_to :user
  belongs_to :merchandise
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :merchandises
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :merchandises
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :merchandise

  validates :comment, presence: true

  def calc_date
    ago_hour = ((Time.now - self.created_at.in_time_zone('Tokyo'))/3600).floor
    if ago_hour < 24
      "#{ago_hour}時間前"
    else
      "#{ago_hour/24}日前"
    end
  end
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
      {id: 1, value: "新品、未使用"}, {id: 2, value: "未使用に近い"}, {id: 3, value: "目立った傷や汚れなし"},
      {id: 4, value: "やや傷や汚れあり"}, {id: 5, value: "傷や汚れあり"}, {id: 6, value: "傷や汚れあり"}, 
      {id: 7, value: "全体的に状態が悪い"}
  ]
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  belongs_to :merchandise
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :shipping_charge
  belongs_to_active_hash :delivery_type
  belongs_to_active_hash :shipping_date
  belongs_to_active_hash :shipping_area
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :user
  belongs_to :purchase
end

app/models/exhibit.rb
class Exhibit < ApplicationRecord
  has_many :to_does, dependent: :destroy
  has_many :exhibit_images, dependent: :destroy
  belongs_to :user
  belongs_to :merchandise

  # 引数に渡した商品の出品者の他の商品を配列itemsに格納して渡す。
  # 現在表示している商品は省き、最大6件まで表示する。
  def user_new_items
    items = []
    Exhibit.where(user_id: self.user_id).limit(7).order(created_at: "DESC").each do |item|
      if item.merchandise.id == self.id
        next
      elsif items.length < 6
        items << item
      else
        break
      end
    end
    items
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :size
end

app/models/guide.rb
class Guide < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :merchandise

  # 一つの商品に対して一回のいいねしかできないようにする
  validates :user_id, uniqueness: {scope: :merchandise_id}

  # valueは 1 のみしか許可しない
  validates :value, numericality: {equal_to: 1}
end

app/models/news.rb
class News < ApplicationRecord
  
end

app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :user
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  has_one :evaluation, dependent: :destroy
  has_many :to_does, dependent: :destroy
  belongs_to :merchandise

  validates :merchandise_id, uniqueness: true
end

app/models/remittee.rb
class Remittee < ApplicationRecord
  belongs_to :personal_information
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
      {id: 1, value: "XXS以下"}, {id: 2, value: "XS(SS)"}, {id: 3, value: "S"}, 
      {id: 4, value: "M"}, {id: 5, value: "L"}, {id: 6, value: "XL(LL)"}, {id: 7, value: "2XL(3L)"},
      {id: 8, value: "3XL(4L)"}, {id: 9, value: "4XL(5L)以上"}, {id: 10, value: "FREE SIZE"}
  ]
end

app/models/to_do.rb
class ToDo < ApplicationRecord
  belongs_to :user
  belongs_to :exhibit
  belongs_to :purchase
  belongs_to :merchandise
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_one :personal_information, dependent: :destroy
  has_one :guide, dependent: :destroy
  has_one :credit_card, dependent: :destroy
  has_one :dealed_comment, dependent: :destroy
  has_one :address, dependent: :destroy
  has_many :points, dependent: :destroy
  has_many :notices, dependent: :destroy
  has_many :to_does, dependent: :destroy
  has_many :balances, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :exhibits, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :purchases, dependent: :destroy
  has_many :evaluations, dependent: :destroy

  # step1入力項目
  validates :nickname,                presence: true, length: {maximum: 20}
  validates :email,                   presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password,                presence: true, length: {minimum: 7, maximum: 128}, on: :create
  validates :password,                presence: true, length: {minimum: 7, maximum: 128}, on: :update, allow_blank: true
  validates :password_confirmation,   presence: true, length: {minimum: 7, maximum: 128}, on: :create
  validates :password_confirmation,   presence: true, length: {minimum: 7, maximum: 128}, on: :update, allow_blank: true
  validates :last_name,               presence: true
  validates :first_name,              presence: true
  validates :last_name_kana,          presence: true
  validates :first_name_kana,         presence: true
  validates :birth_year,              presence: true
  validates :birth_month,             presence: true
  validates :birth_day,               presence: true

  # step2入力項目
  validates :phone_number,            presence: true, uniqueness: true, length: {minimum: 10, maximum: 11}, format: { with: /\A\d{10,11}\z/ }, on: :validates_step2

  def get_full_name
    self.last_name + ' ' + self.first_name
  end

  has_many :sns_credentials, dependent: :destroy

  # protected
  def self.find_for_oauth(auth)
    oauth_user = SnsCredential.find_for_oauth_user(auth)
    
    if oauth_user
      user = oauth_user.user
    else
      if auth.info.email
        user = User.new(email: auth.info.email, password: Devise.friendly_token[0, 20])
      else
        user = User.new(email: "#{auth.provider}_#{auth.uid}@example.com", password: Devise.friendly_token[0, 20])
      end
    end
    user
  end
end

app/controllers/exhibit_list_controller.rb
class ExhibitListController < ApplicationController

  # 出品中の商品
  def list
    @exhibit_list = Exhibit.where(user_id: current_user.id, status: 1)
  end

  # 取引中の商品
  def dealing
    @exhibit_list = Exhibit.where(user_id: current_user.id, status: 2)
  end

  # 売却済みの商品
  def complete
    @exhibit_list = Exhibit.where(user_id: current_user.id, status: 3)
  end
end

app/views/exhibit_list/complete.html.haml
= render 'layouts/header_responsive'
= render 'layouts/header'

.mypage
  .mypage__tab
    .mypage__tab__header.bold
      出品した商品
    %ul.mypage__tab__tabs
      = link_to mypage_exhibit_list_list_path, class: 'mypage__tab__tabs__link' do
        出品中
      = link_to mypage_exhibit_list_dealing_path, class: 'mypage__tab__tabs__link' do
        取引中
      = link_to mypage_exhibit_list_complete_path, class: 'mypage__tab__tabs__link--active' do
        売却済み
    
    .mypage__tab__content
      - unless @exhibit_list.exists?
        .not-found.bold
          売却済みの商品がありません
        
      - else
        .exhibits
          - @exhibit_list.each do |exhibit|
            .exhibit-field
              = link_to exhibit_path(exhibit) do
                .exhibit-field__img
                  = image_tag "#{exhibit.exhibit_images.first.image}", class: 'exhibit-field__img__image'
                .exhibit-field__name
                  = exhibit.merchandise.name

  = render "mypage/menu"

app/views/exhibit_list/dealing.html.haml
= render 'layouts/header_responsive'
= render 'layouts/header'

.mypage
  .mypage__tab
    .mypage__tab__header.bold
      出品した商品
    %ul.mypage__tab__tabs
      = link_to mypage_exhibit_list_list_path, class: 'mypage__tab__tabs__link' do
        出品中
      = link_to mypage_exhibit_list_dealing_path, class: 'mypage__tab__tabs__link--active' do
        取引中
      = link_to mypage_exhibit_list_complete_path, class: 'mypage__tab__tabs__link' do
        売却済み
    
    .mypage__tab__content
      - unless @exhibit_list.exists?
        .not-found.bold
          取引中の商品がありません
        
      - else
        .exhibits
          - @exhibit_list.each do |exhibit|
            .exhibit-field
              = link_to exhibit_path(exhibit) do
                .exhibit-field__img
                  = image_tag "#{exhibit.exhibit_images.first.image}", class: 'exhibit-field__img__image'
                .exhibit-field__name
                  = exhibit.merchandise.name

  = render "mypage/menu"

app/views/exhibit_list/list.html.haml
= render 'layouts/header_responsive'
= render 'layouts/header'

.mypage
  .mypage__tab
    .mypage__tab__header.bold
      出品した商品
    .mypage__tab__tabs
      = link_to mypage_exhibit_list_list_path, class: 'mypage__tab__tabs__link--active' do
        出品中
      = link_to mypage_exhibit_list_dealing_path, class: 'mypage__tab__tabs__link' do
        取引中
      = link_to mypage_exhibit_list_complete_path, class: 'mypage__tab__tabs__link' do
        売却済み
    
    .mypage__tab__content
      - unless @exhibit_list.exists?
        .not-found.bold
          出品中の商品がありません
        
      - else
        .exhibits
          - @exhibit_list.each do |exhibit|
            .exhibit-field
              = link_to exhibit_path(exhibit) do
                .exhibit-field__img
                  = image_tag "#{exhibit.exhibit_images.first.image}", class: 'exhibit-field__img__image'
                .exhibit-field__name
                  = exhibit.merchandise.name

  = render "mypage/menu"