config/routes.rb
Rails.application.routes.draw do
  
  root 'merchandises#index'

  resources :signup do
    collection do
      get 'step1'
      post 'step2'
      post 'step3'
      post 'step4'
      post 'step5'
    end
  end

  
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }
  
  resources :credit_card, only: [:create]
  resources :merchandises, only: [:index, :show] do
    resources :comments, only: [:create, :new]
    resources :likes, only: [:create, :destroy]
    resources :purchase, only: [:index, :create]
  end

  resources :exhibits, only: [:index, :create, :edit, :update, :show, :destroy] do
    collection do
      get 'get_category_children', defaults: { format: 'json'}
    end
  end

  resources :mypage, only: [:index]
  get '/mypage/profile' => 'mypage#edit'
  get '/mypage/card' => 'mypage#show'
  get '/mypage/card/create' => 'mypage#create'
  patch '/mypage' => 'mypage#update'
  get '/mypage/exhibit_list/list' => 'exhibit_list#list'
  get '/mypage/exhibit_list/dealing' => 'exhibit_list#dealing'
  get '/mypage/exhibit_list/complete' => 'exhibit_list#complete'

  resources :personal_informations, only: [:new, :create, :edit, :update]

  get '/signup' => 'signup#index'
  get '/logout' => 'logout#log_out'

  
end

app/models/address.rb
class Address < ApplicationRecord
  #validation制御回避のため、user_idに対してoptional: trueをつける
  belongs_to :user , optional: true

  def get_full_address
    self.prefecture.name + self.city + self.number
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  # step3入力項目
  validates :last_name,               presence: true
  validates :first_name,              presence: true
  validates :last_name_kana,          presence: true
  validates :first_name_kana,         presence: true
  validates :postal_code,             presence: true, format: { with: /\A\d{3}[-]\d{4}\z/ }
  validates :prefecture_id,           presence: true
  validates :city,                    presence: true
  validates :number,                  presence: true

end

app/models/balance.rb
class Balance < ApplicationRecord
  belongs_to :user
  belongs_to :merchandise
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :merchandises
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :merchandises
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :merchandise

  validates :comment, presence: true

  def calc_date
    ago_hour = ((Time.now - self.created_at.in_time_zone('Tokyo'))/3600).floor
    if ago_hour < 24
      "#{ago_hour}時間前"
    else
      "#{ago_hour/24}日前"
    end
  end
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
      {id: 1, value: "新品、未使用"}, {id: 2, value: "未使用に近い"}, {id: 3, value: "目立った傷や汚れなし"},
      {id: 4, value: "やや傷や汚れあり"}, {id: 5, value: "傷や汚れあり"}, {id: 6, value: "傷や汚れあり"}, 
      {id: 7, value: "全体的に状態が悪い"}
  ]
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  belongs_to :merchandise
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :shipping_charge
  belongs_to_active_hash :delivery_type
  belongs_to_active_hash :shipping_date
  belongs_to_active_hash :shipping_area
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :user
  belongs_to :purchase
end

app/models/exhibit.rb
class Exhibit < ApplicationRecord
  has_many :to_does, dependent: :destroy
  has_many :exhibit_images, dependent: :destroy
  belongs_to :user
  belongs_to :merchandise

  # 引数に渡した商品の出品者の他の商品を配列itemsに格納して渡す。
  # 現在表示している商品は省き、最大6件まで表示する。
  def user_new_items
    items = []
    Exhibit.where(user_id: self.user_id).limit(7).order(created_at: "DESC").each do |item|
      if item.merchandise.id == self.id
        next
      elsif items.length < 6
        items << item
      else
        break
      end
    end
    items
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
    belongs_to_active_hash :size
end

app/models/guide.rb
class Guide < ApplicationRecord
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :merchandise

  # 一つの商品に対して一回のいいねしかできないようにする
  validates :user_id, uniqueness: {scope: :merchandise_id}

  # valueは 1 のみしか許可しない
  validates :value, numericality: {equal_to: 1}
end

app/models/news.rb
class News < ApplicationRecord
  
end

app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :user
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  has_one :evaluation, dependent: :destroy
  has_many :to_does, dependent: :destroy
  belongs_to :merchandise

  validates :merchandise_id, uniqueness: true
end

app/models/remittee.rb
class Remittee < ApplicationRecord
  belongs_to :personal_information
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
      {id: 1, value: "XXS以下"}, {id: 2, value: "XS(SS)"}, {id: 3, value: "S"}, 
      {id: 4, value: "M"}, {id: 5, value: "L"}, {id: 6, value: "XL(LL)"}, {id: 7, value: "2XL(3L)"},
      {id: 8, value: "3XL(4L)"}, {id: 9, value: "4XL(5L)以上"}, {id: 10, value: "FREE SIZE"}
  ]
end

app/models/to_do.rb
class ToDo < ApplicationRecord
  belongs_to :user
  belongs_to :exhibit
  belongs_to :purchase
  belongs_to :merchandise
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  has_one :personal_information, dependent: :destroy
  has_one :guide, dependent: :destroy
  has_one :credit_card, dependent: :destroy
  has_one :dealed_comment, dependent: :destroy
  has_one :address, dependent: :destroy
  has_many :points, dependent: :destroy
  has_many :notices, dependent: :destroy
  has_many :to_does, dependent: :destroy
  has_many :balances, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :exhibits, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :purchases, dependent: :destroy
  has_many :evaluations, dependent: :destroy

  # step1入力項目
  validates :nickname,                presence: true, length: {maximum: 20}
  validates :email,                   presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password,                presence: true, length: {minimum: 7, maximum: 128}, on: :create
  validates :password,                presence: true, length: {minimum: 7, maximum: 128}, on: :update, allow_blank: true
  validates :password_confirmation,   presence: true, length: {minimum: 7, maximum: 128}, on: :create
  validates :password_confirmation,   presence: true, length: {minimum: 7, maximum: 128}, on: :update, allow_blank: true
  validates :last_name,               presence: true
  validates :first_name,              presence: true
  validates :last_name_kana,          presence: true
  validates :first_name_kana,         presence: true
  validates :birth_year,              presence: true
  validates :birth_month,             presence: true
  validates :birth_day,               presence: true

  # step2入力項目
  validates :phone_number,            presence: true, uniqueness: true, length: {minimum: 10, maximum: 11}, format: { with: /\A\d{10,11}\z/ }, on: :validates_step2

  def get_full_name
    self.last_name + ' ' + self.first_name
  end

  has_many :sns_credentials, dependent: :destroy

  # protected
  def self.find_for_oauth(auth)
    oauth_user = SnsCredential.find_for_oauth_user(auth)
    
    if oauth_user
      user = oauth_user.user
    else
      if auth.info.email
        user = User.new(email: auth.info.email, password: Devise.friendly_token[0, 20])
      else
        user = User.new(email: "#{auth.provider}_#{auth.uid}@example.com", password: Devise.friendly_token[0, 20])
      end
    end
    user
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController

  before_action :move_to_root_path

  def index
    
  end

  def edit
  end

  def show

  end

  def create
  end

  def update
    if current_user.update(user_params)
      flash[:alert] = "変更しました"
      redirect_to mypage_profile_path
    else
      render :edit
    end
  end

private

  def user_params
    params.require(:user).permit(:nickname, :profile_description)
  end

  def move_to_root_path
    redirect_to root_path unless user_signed_in?
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/views/mypage/_menu.html.haml
%nav.menu
  %ul.menu__links
    %li.menu__links__box
      = link_to mypage_index_path ,class: "menu__links__box__link" do
        マイページ
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to "https://www.mercari.com/jp/mypage/notification/" ,class: "menu__links__box__link" do
        お知らせ
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to "https://www.mercari.com/jp/mypage/todo/" ,class: "menu__links__box__link" do
        やることリスト
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to "https://www.mercari.com/jp/mypage/like/history/" ,class: "menu__links__box__link" do
        いいね！一覧
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to exhibits_path ,class: "menu__links__box__link" do
        出品する
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to mypage_exhibit_list_list_path, class: "menu__links__box__link" do
        出品した商品 - 出品中
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to mypage_exhibit_list_dealing_path, class: "menu__links__box__link" do
        出品した商品 - 取引中
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to mypage_exhibit_list_complete_path, class: "menu__links__box__link" do
        出品した商品 - 売却済み
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to "https://www.mercari.com/jp/mypage/purchase/" ,class: "menu__links__box__link" do
        購入した商品 - 取引中
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to "https://www.mercari.com/jp/mypage/purchased/" ,class: "menu__links__box__link" do
        購入した商品 - 過去の取引
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to "https://www.mercari.com/jp/mypage/news/" ,class: "menu__links__box__link" do
        ニュース一覧
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to "https://www.mercari.com/jp/mypage/review/history/" ,class: "menu__links__box__link" do
        評価一覧
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to "https://www.mercari.com/jp/help_center/" ,class: "menu__links__box__link" do
        ガイド
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to "https://www.mercari.com/jp/mypage/support/" ,class: "menu__links__box__link" do
        お問い合わせ
        = fa_icon "chevron-right", class: "menu__links__box__angle"

  %h3.menu__header.bold
    メルペイ
  %ul.menu__links
    %li.menu__links__box
      = link_to "https://www.mercari.com/jp/mypage/sales/" ,class: "menu__links__box__link" do
        売上・振込申請
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to "https://www.mercari.com/jp/mypage/point/" ,class: "menu__links__box__link" do
        ポイント
        = fa_icon "chevron-right", class: "menu__links__box__angle"

  %h3.menu__header.bold
    設定
    
  %ul.menu__links
    %li.menu__links__box
      = link_to mypage_profile_path ,class: "menu__links__box__link" do
        プロフィール
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to "https://www.mercari.com/jp/mypage/deliver_address/" ,class: "menu__links__box__link" do
        発送元・お届け先住所変更
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to mypage_card_path ,class: "menu__links__box__link" do
        支払い方法
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to "https://www.mercari.com/jp/mypage/email_password/" ,class: "menu__links__box__link" do
        メール/パスワード
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      - if current_user.personal_information.present?
        = link_to edit_personal_information_path(current_user) ,class: "menu__links__box__link" do
          本人情報
          = fa_icon "chevron-right", class: "menu__links__box__angle"
      - else
        = link_to new_personal_information_path ,class: "menu__links__box__link" do
          本人情報
          = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to "https://www.mercari.com/jp/mypage/sms_confirmation/" ,class: "menu__links__box__link" do
        電話番号の確認
        = fa_icon "chevron-right", class: "menu__links__box__angle"
    %li.menu__links__box
      = link_to logout_path ,class: "menu__links__box__link" do
        ログアウト
        = fa_icon "chevron-right", class: "menu__links__box__angle"

app/views/mypage/card.html.haml
-# ヘッダー
= render 'layouts/header_responsive'
= render 'layouts/header'

.mypage
  .mypage__card-create
    .mypage__card-create__section
      %h2.mypage__card-create__section__title  クレジットカード情報入力
      = fields_for :credit_card do |f|
        .contents
          .contents__field
            = f.label :カード番号
            %span.reqiure 必須
            %br/
            = f.text_field :card_number, autofocus: true, autocomplete: "card_number", placeholder: "半角数字のみ"
          %ul
            %li
              = image_tag('visa.svg', class: 'card_logo')
            %li
              = image_tag('master.svg', class: 'card_logo')
            %li
              = image_tag('saison.svg', class: 'card_logo')
            %li
              = image_tag('jcb.svg', class: 'card_logo')
            %li
              = image_tag('american_express.svg', class: 'card_logo')
            %li
              = image_tag('dinersclub.svg', class: 'card_logo')
            %li
              = image_tag('discover.svg', class: 'card_logo')
          .contents__field
            = f.label :有効期限
            %span.reqiure 必須
            = fa_icon "chevron-down", class: "contents__field__allow"
            = fa_icon "chevron-down", class: "contents__field__allow2"
            %br/
            = f.select :birth_month, ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12'], {include_blank: '--'}, class: 'month_selection'
            %span 月
            = f.select :birth_year, ['19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29'], {include_blank: '--'}, class: 'year_selection'
            %span 年
          .contents__field
            = f.label :セキュリティコード
            %span.reqiure 必須
            %br/
            = f.text_field :security_code, autofocus: true, autocomplete: "security_code", placeholder: "カード背面4桁もしくは3桁の番号"
          .contents__field__reason
            %b.contents__field__reason__question?
            カード裏面の番号とは？
            %div.image
              %text.credit-seq_before カードの裏面をご参照ください。
              = image_tag('seq-card.png', class: 'seq-card')
          .contents__field__button
            = f.submit "追加する", class: "form__submit"


  = render "menu"

  -# 出品ボタン
= render 'layouts/exhibit'
-# アプリダウンロードバーナー
= render 'layouts/app-download'
-# フッター
= render 'layouts/footer' 

app/views/mypage/create.html.haml
-# ヘッダー
= render 'layouts/header_responsive'
= render 'layouts/header'

.mypage
  .mypage__card-create
    .mypage__card-create__section
      %h2.mypage__card-create__section__title  クレジットカード情報入力
      = fields_for :credit_card do |f|
        .contents
          .contents__field
            = f.label :カード番号
            %span.reqiure 必須
            %br/
            = f.text_field :card_number, autofocus: true, autocomplete: "card_number", placeholder: "半角数字のみ"
          %ul
            %li
              = image_tag('visa.svg', class: 'card_logo')
            %li
              = image_tag('master.svg', class: 'card_logo')
            %li
              = image_tag('saison.svg', class: 'card_logo')
            %li
              = image_tag('jcb.svg', class: 'card_logo')
            %li
              = image_tag('american_express.svg', class: 'card_logo')
            %li
              = image_tag('dinersclub.svg', class: 'card_logo')
            %li
              = image_tag('discover.svg', class: 'card_logo')
          .contents__field
            = f.label :有効期限
            %span.reqiure 必須
            = fa_icon "chevron-down", class: "contents__field__allow"
            = fa_icon "chevron-down", class: "contents__field__allow2"
            %br/
            = f.select :birth_month, ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12'], {include_blank: '--'}, class: 'month_selection'
            %span 月
            = f.select :birth_year, ['19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29'], {include_blank: '--'}, class: 'year_selection'
            %span 年
          .contents__field
            = f.label :セキュリティコード
            %span.reqiure 必須
            %br/
            = f.text_field :security_code, autofocus: true, autocomplete: "security_code", placeholder: "カード背面4桁もしくは3桁の番号"
          .contents__field__reason
            %b.contents__field__reason__question?
            カード裏面の番号とは？
            %div.image
              %text.credit-seq_before カードの裏面をご参照ください。
              = image_tag('seq-card.png', class: 'seq-card')
          .contents__field__button
            = f.submit "追加する", class: "form__submit"


  = render "menu"

  -# 出品ボタン
= render 'layouts/exhibit'
-# アプリダウンロードバーナー
= render 'layouts/app-download'
-# フッター
= render 'layouts/footer' 

app/views/mypage/edit.html.haml
-# ヘッダー
= render 'layouts/header_responsive'
= render 'layouts/header'

.mypage
  .profile
    %h2.profile__header.bold
      プロフィール
    = form_for current_user, url: mypage_index_path, html: { method: :patch } do |f|
      .profile__form__icon
        = image_tag "https://static.mercdn.net/images/member_photo_noimage_thumb.png", class: "profile__form__icon__image"
        = f.text_field :nickname, placeholder: "例)AYA☆セール中", class: "profile__form__icon__user-name"
      .profile__form__content
        = f.text_area :profile_description, placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪", class: "profile__form__content__discription"
        = f.submit "変更する", class: "profile__form__content__button"

  = render "menu"

  -# 出品ボタン
= render 'layouts/exhibit'
-# アプリダウンロードバーナー
= render 'layouts/app-download'
-# フッター
= render 'layouts/footer'

app/views/mypage/index.html.haml
-# ヘッダー
= render 'layouts/header_responsive'
= render 'layouts/header'

.mypage
  .main
    .user-icon
      = link_to mypage_profile_path, class: "user-icon__link" do
        .user-icon__image-div
          = image_tag "https://static.mercdn.net/images/member_photo_noimage_thumb.png", class: "user-icon__image"
        .user-icon__user-name.bold
          = current_user.nickname
        .user-icon__user-info
          .user-icon__user-evaluation
            評価
            %span.bold
              0
          .user-icon__user-exhibit
            出品数
            %span.bold
              = current_user.exhibits.count

    .notify-todo
      %ul.tab
        %li.bold.active
          お知らせ
        %li.bold
          やることリスト
      .tab-content
        %ul.notify-todo__notify.show
          %li.notify-todo__notify__content
            = link_to "https://www.mercari.com/jp/mypage/news/", class: "notify-todo__notify__content__link" do
              = image_tag "//static.mercdn.net/images/mercari_profile.png", class: "notify-todo__notify__content__icon"
              .notify-todo__notify__content__body
                .notify-todo__notify__content__text
                  事務局から個別メッセージ「《3連休はスパリゾートハワイアンズへ》9月限定！メルペイのコード払いで入場料20%割引！」
                .notify-todo__notify__content__date
                  .notify-todo__notify__content__date__clock-icon
                    = fa_icon "clock-o"
                  .notify-todo__notify__content__date__time
                    5時間前
              = fa_icon "chevron-right", class: "notify-todo__notify__content__angle"
          %li.notify-todo__notify__content
            = link_to "https://www.mercari.com/jp/mypage/news/", class: "notify-todo__notify__content__link" do
              = image_tag "//static.mercdn.net/images/mercari_profile.png", class: "notify-todo__notify__content__icon"
              .notify-todo__notify__content__body
                .notify-todo__notify__content__text
                  事務局から個別メッセージ「《3連休はスパリゾートハワイアンズへ》9月限定！メルペイのコード払いで入場料20%割引！」
                .notify-todo__notify__content__date
                  .notify-todo__notify__content__date__clock-icon
                    = fa_icon "clock-o"
                  .notify-todo__notify__content__date__time
                    5時間前
              = fa_icon "chevron-right", class: "notify-todo__notify__content__angle"
          %li.notify-todo__notify__content
            = link_to "https://www.mercari.com/jp/mypage/news/", class: "notify-todo__notify__content__link" do
              = image_tag "//static.mercdn.net/images/mercari_profile.png", class: "notify-todo__notify__content__icon"
              .notify-todo__notify__content__body
                .notify-todo__notify__content__text
                  事務局から個別メッセージ「《3連休はスパリゾートハワイアンズへ》9月限定！メルペイのコード払いで入場料20%割引！」
                .notify-todo__notify__content__date
                  .notify-todo__notify__content__date__clock-icon
                    = fa_icon "clock-o"
                  .notify-todo__notify__content__date__time
                    5時間前
              = fa_icon "chevron-right", class: "notify-todo__notify__content__angle"
          .notify-todo__notify__go-list
            = link_to "一覧を見る", "https://www.mercari.com/jp/mypage/notification/", class:"notify-todo__notify__go-list__link"
        %ul.notify-todo__todo
          %li.not-found.bold
            現在、やることリストはありません

    .purchased
      .purchased__header.bold
        購入した商品
      %ul.tab
        %li.bold.active
          取引中
        %li.bold
          過去の取引
      .tab-content
        %ul.purchased__dealing__content.show
          %li.not-found.bold
            取引中の商品がありません
        %ul.purchased__dealed__content
          %li.not-found.bold
            過去に取引した商品がありません

  = render "menu"

  -# 出品ボタン
= render 'layouts/exhibit'
-# アプリダウンロードバーナー
= render 'layouts/app-download'
-# フッター
= render 'layouts/footer'

app/views/mypage/new.html.haml
-# ヘッダー
= render 'layouts/header_responsive'
= render 'layouts/header'

.mypage
  .mypage__identification
    %h2.mypage__identification__header
      本人情報の登録
    = fields_for :Address do |f|
      .contents
        .contents__information
          %p お客さまの本人情報をご登録ください。
          %p 登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
          .contents__information__upload
            = link_to "https://www.mercari.com/jp/help_center/article/495/", target: :_blank , class:"link" do
              本人確認書類のアップロードについて
              %i.fa.fa-angle-right
        .contents__field
          = f.label "お名前"
          %p.form__contents ◯◯ ◯◯
        .contents__field
          = f.label "お名前カナ"
          %p.form__contents ◯◯ ◯◯
        .contents__field
          = f.label "生年月日"
          %p.form__contents 2000/01/01
        .contents__field
          = f.label :郵便番号
          %span.optional 任意
          = f.text_field :postal_code, autocomplete: "postal_code", placeholder: "例)123-4567"
        .contents__field
          = f.label :都道府県
          %span.optional 任意
          = fa_icon "chevron-down", class: "aicon-arrow-bottom"
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {include_blank: '--'}, class: 'prefecture'
        .contents__field
          = f.label :市区町村
          %span.optional 任意
          = f.text_field :city, autocomplete: "city", placeholder: "例)横浜市緑区"
        .contents__field
          = f.label :番地
          %span.optional 任意
          = f.text_field :number, autocomplete: "number", placeholder: "例)青山1-1-1"
        .contents__field
          = f.label :建物名
          %span.optional 任意
          = f.text_field :building, autocomplete: "building", placeholder: "例)柳ビル103"
        .contents__field
          .contents__field__button
            = f.submit "登録する", class: "form__submit"
          .text-right
            %p.text__personal
              = link_to "https://www.mercari.com/jp/help_center/article/423/", target: :_blank , class:"link" do
                本人情報の登録について
                = fa_icon 'angle-right'

  
  = render "menu"

  -# 出品ボタン
= render 'layouts/exhibit'
-# アプリダウンロードバーナー
= render 'layouts/app-download'
-# フッター
= render 'layouts/footer' 

app/views/mypage/show.html.haml
-# ヘッダー
= render 'layouts/header_responsive'
= render 'layouts/header'

.mypage
  .mypage__card
    %h2.mypage__card__header
      支払い方法
    .contents
      .contents__field
        .contents__field__title
          クレジットカード一覧
      .contents__field
        = link_to "/mypage/card/create", class:"contents__field__button" do
          = fa_icon 'credit-card' , class:"contents__field__card"
          クレジットカードを追加する
      .contents__text
        %p.contents__text__method
          = link_to "https://www.mercari.com/jp/help_center/category/6/", target: :_blank , class:"contents__text__method__link" do
            支払い方法について
            = fa_icon 'angle-right' , class:"contents__text__method__allow"

  
  = render "menu"

  -# 出品ボタン
= render 'layouts/exhibit'
-# アプリダウンロードバーナー
= render 'layouts/app-download'
-# フッター
= render 'layouts/footer' 